#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
: "${QUANTIZATION_MODE:=int8-a8w8}"
: "${TORCH_NUM_THREADS:=2}"
: "${TORCH_NUM_INTEROP_THREADS:=1}"
: "${RERANKER_MICROBATCH_SIZE:=1}"
: "${EMBEDDING_MICROBATCH_SIZE:=1}"
: "${MODEL_DTYPE:=float16}"
export QUANTIZATION_MODE TORCH_NUM_THREADS TORCH_NUM_INTEROP_THREADS
export RERANKER_MICROBATCH_SIZE EMBEDDING_MICROBATCH_SIZE MODEL_DTYPE
export MAX_CONCURRENT_INFERENCE=1 MAX_SEQ_LENGTH=512
export ALLOW_REMOTE_MODEL_DOWNLOAD=0 HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1 TOKENIZERS_PARALLELISM=false
exec "$ROOT/scripts/start-server.sh"
